// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqpuxmlvjrbiuhkniwvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxcHV4bWx2anJiaXVoa25pd3ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NTM4NzYsImV4cCI6MjA2NTIyOTg3Nn0.Qi6DWEQiI7bKwB6CGHWiGYPHB645bpyvdltMWkVonD4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);